# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f74d5d744060ae99120001308f400d51b451b81dbb7b1638704f715aabc8b120ea0f89243f54199a6fe34969087df202e27312b2f00963fadb5bc1d4117ec69

test:
  secret_key_base: 83290177c36f541dd7bde9a87d7de1ab4728dbf590e2105799158647fc09669c38a18471b40a945ca20b5b556c0412e8c495c53c05142aa87db944727c1dc1f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
